-- database/schema.sql

CREATE DATABASE IF NOT EXISTS student_retention_db;
USE student_retention_db;

-- 1. Users Table (Admin, Instructor, Student)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, -- Can be student_no or staff ID
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('Admin', 'Instructor', 'Student') NOT NULL,
    email VARCHAR(100) UNIQUE
);

-- 2. Academic Records Table
CREATE TABLE IF NOT EXISTS academic_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    gpa DECIMAL(3,2),
    attendance DECIMAL(5,2),
    quiz_score DECIMAL(5,2),
    assignment_score DECIMAL(5,2),
    semester VARCHAR(50),
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. AI Predictions Table
CREATE TABLE IF NOT EXISTS predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    risk_probability DECIMAL(5,4),
    is_at_risk BOOLEAN,
    prediction_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. Notifications & Alerts Table (Smart Notes)
CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    instructor_id INT, -- Can be NULL if generated by the system automatically
    course_name VARCHAR(100),
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (instructor_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 5. System Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    user_role ENUM('Admin', 'Instructor', 'Student') NOT NULL, -- Important for filtering
    action VARCHAR(255) NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Example Query for Admin: Extract Student Logs Only
-- SELECT a.id, u.username, a.action, a.timestamp 
-- FROM audit_logs a
-- JOIN users u ON a.user_id = u.id
-- WHERE a.user_role = 'Student'
-- ORDER BY a.timestamp DESC;